### ISSUE TITLE
Add array support

### ISSUE THREAD

**Issue by sylphy-zh** [lalinsky/python-phoenixdb#3]
If I create table 'USER', and it's schema defined 'PERSONA'. 
```python
database_url = "http://master:8765/"
conn = phoenixdb.connect(database_url, autocommit=True)
cursor = conn.cursor()
cursor.execute("SELECT * FROM USER")
```
It has a error: Table undefined , tableName='USER'.
But When I use below query:
```
SELECT * FROM PERSON.USER
```
this will have a ERROR: UnsupportedOperationException: Currently not supported.

When I see the source code and not found anywhere I can specify the schema parameter.

How to solve this? Any idea?

**Comment by lalinsky** [comment]
How did you get the query server running with schema support? I'm trying to do it myself, but I'm failing on this:

```
Inconsistent namespace mapping properites.. Ensure that config phoenix.schema.isNamespaceMappingEnabled is consitent on client and server.
```

Can you please share how are you running the query server?

**Comment by lalinsky** [comment]
I have added a test to check that schema support works:

https://github.com/lalinsky/python-phoenixdb/commit/424a3751d25a1073a4dedcf454ab044d9f900aa1

I'm unable to reproduce your problem. Can you please describe how are you running HBase/Phoenix?

**Comment by singledoublemonkey** [comment]
@lalinsky Thanks. In my env(Python =>2.7.  phoenixdb => 0.7, phoenix =>4.9), running the query server:  
```
/path/to/phoenix/bin/queryserver.py start 
```
When I use '~/bin/sqlline.py'  exec the same command to query , that's work fine.  
```
jdbc:phoenix:> select * from PERSON.USER;
+-----------+--------+-----------+-------------+---------------------------------------+--------------+---------+
|    UID    | DEPTH  |    SR     | ACTIVE_DAY  |               APP_LIST                | START_COUNT  |   NTM   |
+-----------+--------+-----------+-------------+---------------------------------------+--------------+---------+
| 34643599  | 9.1    | 1024x768  | 6           | ['QQ', 'Weixin', 'nongyao']           | 21           | Mobile  |
| 12345623  | 10.5   | 1024x768  | 5           | ['Apple', 'YY', 'QQ', 'Weixin']       | 20           | Mobile  |
| 35634525  | 6.8    | 256x768   | 8           | ['YY', 'QQ', 'Weixin', 'Xiaoxiaole']  | 16           | Mobile  |
| 56772345  | 6.5    | 256x768   | 8           | ['QQ', 'Weixin', 'Xiaoxiaole']        | 13           | Mobile  |
| 34652477  | 3.5    | 256x768   | 8           | ['QQ', 'Weixin', 'nongyao']           | 17           | Mobile  |
+-----------+--------+-----------+-------------+---------------------------------------+--------------+---------+
```

When I use the queryserver, It's wrong. 
``` python
import phoenixdb
import phoenixdb.cursor

database_url = "http://master:8765/"
conn = phoenixdb.connect(database_url, autocommit=True)
cursor = conn.cursor()
cursor.execute("SELECT * FROM PERSON.USER")
print cursor.fetchall()
```
Error Message:
```
Traceback (most recent call last):
  File "phoenix-op.py", line 7, in <module>
    cursor.execute("SELECT * FROM PERSON.USER")
  File "build/bdist.linux-x86_64/egg/phoenixdb/cursor.py", line 201, in execute
  File "build/bdist.linux-x86_64/egg/phoenixdb/avatica.py", line 405, in prepare_and_execute
  File "build/bdist.linux-x86_64/egg/phoenixdb/avatica.py", line 216, in _apply
  File "build/bdist.linux-x86_64/egg/phoenixdb/avatica.py", line 129, in parse_error_protobuf
phoenixdb.errors.InternalError: (u'UnsupportedOperationException: Currently not supported', None, None, None
```

**Comment by sylphy-zh** [comment]
@lalinsky Thanks for your response.  When I see some doc found that the phoenixdb is still not support array type field.  Because there have some array type fields in my table, and query the non-array fields is ok.  But when I use /path/to/phoenix/sqlline.py, same query is work fine. 
```
Env : phoenixdb => 0.7
```
phoenixdb use protocol buffer transport default, I don't know whether json is support to use array type fields. Docs seems still not suport now.

**Comment by lalinsky** [comment]
Array support is not implemented yet. It has been added to Avatica/Phoenix since I started working in this project, but the type encoding/decoding code still needs to be updated.
